RAT_m2_tmall_x1_002_retrieval:
    batch_norm: true
    batch_size: 4096
    dataset_id: tmall_x1_002_retrieval
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [200,80]
    embedding_dim: 10
    embedding_regularizer: 0.07
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: RAT_m2
    model_id: RAT_m2_base
    retrieval_augmented: true
    model_root: ./exps/RAT_m2/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.08  
    num_heads: 32
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
    depth: 4
    pool: 'cls'
    dim_head: 10
    dropout: 0.
    emb_dropout: 0.1
    scale_dim:  2